import type { Metadata } from "next"
import { Poppins } from "next/font/google"

import "@blogtron/ui/styles/main.css"

import Providers from "./providers"

const font = Poppins({
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
